import type {
  ChinchillaCoefficients,
  CloudInstance,
  CloudPricingPreset,
  FP8Config,
  GPUSpec,
  LoRATargetModule,
  MFUDefault,
  ModelArchitecture,
  ModelPreset,
  MoEConfig,
  OptimizerProfile,
  ParallelismConfig,
  PostTrainingConfig,
  QuickModeConfig,
  QuickModeLookup,
  TrainingConfig,
  ZeROCommunicationConfig,
} from "./types"

export const GPU_SPECS = [
  {
    id: "v100-32gb",
    name: "V100 32GB",
    vendor: "nvidia",
    category: "nvidia-datacenter",
    memoryType: "vram",
    memoryGB: 32,
    halfPrecisionTFLOPS: 125,
    halfPrecisionFormat: "fp16",
    tf32TFLOPS: null,
    fp32TFLOPS: 15.7,
    fp8TFLOPS: null,
    memoryBandwidthGBps: 900,
    nvlinkBandwidthGBps: 300,
    tdpWatts: 300,
    gpusPerNode: 8,
    interconnect: "nvlink",
    singleDeviceOnly: false,
    supportsBF16: false,
    supportsTF32: false,
    supportsFP8: false,
  },
  {
    id: "a100-pcie-80gb",
    name: "A100 PCIe 80GB",
    vendor: "nvidia",
    category: "nvidia-datacenter",
    memoryType: "vram",
    memoryGB: 80,
    halfPrecisionTFLOPS: 312,
    halfPrecisionFormat: "bf16",
    tf32TFLOPS: 156,
    fp8TFLOPS: null,
    memoryBandwidthGBps: 2039,
    nvlinkBandwidthGBps: null,
    tdpWatts: 300,
    gpusPerNode: 8,
    interconnect: "pcie",
    singleDeviceOnly: false,
    supportsBF16: true,
    supportsTF32: true,
    supportsFP8: false,
  },
  {
    id: "a100-40gb",
    name: "A100 40GB",
    vendor: "nvidia",
    category: "nvidia-datacenter",
    memoryType: "vram",
    memoryGB: 40,
    halfPrecisionTFLOPS: 312,
    halfPrecisionFormat: "bf16",
    tf32TFLOPS: 156,
    fp8TFLOPS: null,
    memoryBandwidthGBps: 1555,
    nvlinkBandwidthGBps: 600,
    tdpWatts: 400,
    gpusPerNode: 8,
    interconnect: "nvlink",
    singleDeviceOnly: false,
    supportsBF16: true,
    supportsTF32: true,
    supportsFP8: false,
  },
  {
    id: "a100-80gb",
    name: "A100 80GB",
    vendor: "nvidia",
    category: "nvidia-datacenter",
    memoryType: "vram",
    memoryGB: 80,
    halfPrecisionTFLOPS: 312,
    halfPrecisionFormat: "bf16",
    tf32TFLOPS: 156,
    fp8TFLOPS: null,
    memoryBandwidthGBps: 2039,
    nvlinkBandwidthGBps: 600,
    tdpWatts: 400,
    gpusPerNode: 8,
    interconnect: "nvlink",
    singleDeviceOnly: false,
    supportsBF16: true,
    supportsTF32: true,
    supportsFP8: false,
  },
  {
    id: "h100-pcie-80gb",
    name: "H100 PCIe 80GB",
    vendor: "nvidia",
    category: "nvidia-datacenter",
    memoryType: "vram",
    memoryGB: 80,
    halfPrecisionTFLOPS: 756,
    halfPrecisionFormat: "bf16",
    tf32TFLOPS: 378,
    fp8TFLOPS: 1513,
    memoryBandwidthGBps: 2039,
    nvlinkBandwidthGBps: null,
    tdpWatts: 350,
    gpusPerNode: 8,
    interconnect: "pcie",
    singleDeviceOnly: false,
    supportsBF16: true,
    supportsTF32: true,
    supportsFP8: true,
  },
  {
    id: "h100-sxm",
    name: "H100 SXM",
    vendor: "nvidia",
    category: "nvidia-datacenter",
    memoryType: "vram",
    memoryGB: 80,
    halfPrecisionTFLOPS: 989,
    halfPrecisionFormat: "bf16",
    tf32TFLOPS: 495,
    fp8TFLOPS: 1979,
    memoryBandwidthGBps: 3350,
    nvlinkBandwidthGBps: 900,
    tdpWatts: 700,
    gpusPerNode: 8,
    interconnect: "nvlink",
    singleDeviceOnly: false,
    supportsBF16: true,
    supportsTF32: true,
    supportsFP8: true,
  },
  {
    id: "h100-nvl",
    name: "H100 NVL",
    vendor: "nvidia",
    category: "nvidia-datacenter",
    memoryType: "vram",
    memoryGB: 94,
    halfPrecisionTFLOPS: 835,
    halfPrecisionFormat: "bf16",
    tf32TFLOPS: 418,
    fp8TFLOPS: 1671,
    memoryBandwidthGBps: 3938,
    nvlinkBandwidthGBps: 600,
    tdpWatts: 400,
    gpusPerNode: 8,
    interconnect: "nvlink",
    singleDeviceOnly: false,
    supportsBF16: true,
    supportsTF32: true,
    supportsFP8: true,
  },
  {
    id: "h200-sxm",
    name: "H200 SXM",
    vendor: "nvidia",
    category: "nvidia-datacenter",
    memoryType: "vram",
    memoryGB: 141,
    halfPrecisionTFLOPS: 989,
    halfPrecisionFormat: "bf16",
    tf32TFLOPS: 495,
    fp8TFLOPS: 1979,
    memoryBandwidthGBps: 4800,
    nvlinkBandwidthGBps: 900,
    tdpWatts: 700,
    gpusPerNode: 8,
    interconnect: "nvlink",
    singleDeviceOnly: false,
    supportsBF16: true,
    supportsTF32: true,
    supportsFP8: true,
  },
  {
    id: "b200-hgx",
    name: "B200 (HGX)",
    vendor: "nvidia",
    category: "nvidia-datacenter",
    memoryType: "vram",
    memoryGB: 180,
    halfPrecisionTFLOPS: 2250,
    halfPrecisionFormat: "bf16",
    tf32TFLOPS: 1125,
    fp8TFLOPS: 4500,
    memoryBandwidthGBps: 8000,
    nvlinkBandwidthGBps: 1800,
    tdpWatts: 1000,
    gpusPerNode: 8,
    interconnect: "nvlink",
    singleDeviceOnly: false,
    supportsBF16: true,
    supportsTF32: true,
    supportsFP8: true,
  },
  {
    id: "b200-nvl72",
    name: "B200 (NVL72)",
    vendor: "nvidia",
    category: "nvidia-datacenter",
    memoryType: "vram",
    memoryGB: 186,
    halfPrecisionTFLOPS: 2500,
    halfPrecisionFormat: "bf16",
    tf32TFLOPS: 1250,
    fp8TFLOPS: 5000,
    memoryBandwidthGBps: 8000,
    nvlinkBandwidthGBps: 1800,
    tdpWatts: 1200,
    gpusPerNode: 72,
    interconnect: "nvlink",
    singleDeviceOnly: false,
    supportsBF16: true,
    supportsTF32: true,
    supportsFP8: true,
  },
  {
    id: "mi250x",
    name: "MI250X",
    vendor: "amd",
    category: "amd-datacenter",
    memoryType: "vram",
    memoryGB: 128,
    halfPrecisionTFLOPS: 383,
    halfPrecisionFormat: "bf16",
    tf32TFLOPS: null,
    fp32TFLOPS: 47.9,
    fp8TFLOPS: null,
    memoryBandwidthGBps: 3276,
    nvlinkBandwidthGBps: null,
    tdpWatts: 560,
    gpusPerNode: 8,
    interconnect: "xgmi",
    singleDeviceOnly: false,
    supportsBF16: true,
    supportsTF32: false,
    supportsFP8: false,
  },
  {
    id: "mi300x",
    name: "MI300X",
    vendor: "amd",
    category: "amd-datacenter",
    memoryType: "vram",
    memoryGB: 192,
    halfPrecisionTFLOPS: 1307.4,
    halfPrecisionFormat: "bf16",
    tf32TFLOPS: 653.7,
    fp8TFLOPS: 2614.9,
    memoryBandwidthGBps: 5325,
    nvlinkBandwidthGBps: null,
    tdpWatts: 750,
    gpusPerNode: 8,
    interconnect: "xgmi",
    singleDeviceOnly: false,
    supportsBF16: true,
    supportsTF32: true,
    supportsFP8: true,
  },
  {
    id: "l40s",
    name: "L40S",
    vendor: "nvidia",
    category: "nvidia-datacenter",
    memoryType: "vram",
    memoryGB: 48,
    halfPrecisionTFLOPS: 362,
    halfPrecisionFormat: "bf16",
    tf32TFLOPS: 183,
    fp8TFLOPS: 733,
    memoryBandwidthGBps: 864,
    nvlinkBandwidthGBps: null,
    tdpWatts: 350,
    gpusPerNode: 8,
    interconnect: "pcie",
    singleDeviceOnly: false,
    supportsBF16: true,
    supportsTF32: true,
    supportsFP8: true,
  },
  {
    id: "rtx-4090",
    name: "RTX 4090",
    vendor: "nvidia",
    category: "nvidia-consumer",
    memoryType: "vram",
    memoryGB: 24,
    halfPrecisionTFLOPS: 165.2,
    halfPrecisionFormat: "bf16",
    tf32TFLOPS: 82.6,
    fp8TFLOPS: 330.3,
    memoryBandwidthGBps: 1008,
    nvlinkBandwidthGBps: null,
    tdpWatts: 450,
    gpusPerNode: 1,
    interconnect: "pcie",
    singleDeviceOnly: false,
    supportsBF16: true,
    supportsTF32: true,
    supportsFP8: true,
  },
  {
    id: "rtx-4080",
    name: "RTX 4080",
    vendor: "nvidia",
    category: "nvidia-consumer",
    memoryType: "vram",
    memoryGB: 16,
    halfPrecisionTFLOPS: 97.5,
    halfPrecisionFormat: "bf16",
    tf32TFLOPS: 48.7,
    fp8TFLOPS: 194.9,
    memoryBandwidthGBps: 716.8,
    nvlinkBandwidthGBps: null,
    tdpWatts: 320,
    gpusPerNode: 1,
    interconnect: "pcie",
    singleDeviceOnly: false,
    supportsBF16: true,
    supportsTF32: true,
    supportsFP8: true,
  },
  {
    id: "rtx-3090",
    name: "RTX 3090",
    vendor: "nvidia",
    category: "nvidia-consumer",
    memoryType: "vram",
    memoryGB: 24,
    halfPrecisionTFLOPS: 71,
    halfPrecisionFormat: "bf16",
    tf32TFLOPS: 36,
    fp8TFLOPS: null,
    memoryBandwidthGBps: 936,
    nvlinkBandwidthGBps: 112.5,
    tdpWatts: 350,
    gpusPerNode: 2,
    interconnect: "nvlink",
    singleDeviceOnly: false,
    supportsBF16: true,
    supportsTF32: true,
    supportsFP8: false,
  },
  {
    id: "rtx-3060-12gb",
    name: "RTX 3060 12GB",
    vendor: "nvidia",
    category: "nvidia-consumer",
    memoryType: "vram",
    memoryGB: 12,
    halfPrecisionTFLOPS: 25,
    halfPrecisionFormat: "bf16",
    tf32TFLOPS: 13,
    fp8TFLOPS: null,
    memoryBandwidthGBps: 360,
    nvlinkBandwidthGBps: null,
    tdpWatts: 170,
    gpusPerNode: 1,
    interconnect: "pcie",
    singleDeviceOnly: false,
    supportsBF16: true,
    supportsTF32: true,
    supportsFP8: false,
  },
  {
    id: "t4",
    name: "T4",
    vendor: "nvidia",
    category: "nvidia-datacenter",
    memoryType: "vram",
    memoryGB: 16,
    halfPrecisionTFLOPS: 65,
    halfPrecisionFormat: "fp16",
    tf32TFLOPS: null,
    fp32TFLOPS: 8.1,
    fp8TFLOPS: null,
    memoryBandwidthGBps: 320,
    nvlinkBandwidthGBps: null,
    tdpWatts: 70,
    gpusPerNode: 4,
    interconnect: "pcie",
    singleDeviceOnly: false,
    supportsBF16: false,
    supportsTF32: false,
    supportsFP8: false,
  },
  {
    id: "a10g",
    name: "A10G",
    vendor: "nvidia",
    category: "nvidia-datacenter",
    memoryType: "vram",
    memoryGB: 24,
    halfPrecisionTFLOPS: 70,
    halfPrecisionFormat: "bf16",
    tf32TFLOPS: 35,
    fp8TFLOPS: null,
    memoryBandwidthGBps: 600,
    nvlinkBandwidthGBps: null,
    tdpWatts: 300,
    gpusPerNode: 8,
    interconnect: "pcie",
    singleDeviceOnly: false,
    supportsBF16: true,
    supportsTF32: true,
    supportsFP8: false,
  },
  {
    id: "l4",
    name: "L4",
    vendor: "nvidia",
    category: "nvidia-datacenter",
    memoryType: "vram",
    memoryGB: 24,
    halfPrecisionTFLOPS: 121,
    halfPrecisionFormat: "bf16",
    tf32TFLOPS: 60,
    fp8TFLOPS: 242,
    memoryBandwidthGBps: 300,
    nvlinkBandwidthGBps: null,
    tdpWatts: 72,
    gpusPerNode: 8,
    interconnect: "pcie",
    singleDeviceOnly: false,
    supportsBF16: true,
    supportsTF32: true,
    supportsFP8: true,
  },
  {
    id: "m1-max",
    name: "M1 Max",
    vendor: "apple",
    category: "apple-silicon",
    memoryType: "unified",
    memoryGB: 64,
    halfPrecisionTFLOPS: 10.4,
    halfPrecisionFormat: "fp16",
    tf32TFLOPS: null,
    fp32TFLOPS: 10.4,
    fp8TFLOPS: null,
    memoryBandwidthGBps: 400,
    nvlinkBandwidthGBps: null,
    tdpWatts: null,
    gpusPerNode: 1,
    interconnect: "none",
    singleDeviceOnly: true,
    supportsBF16: false,
    supportsTF32: false,
    supportsFP8: false,
  },
  {
    id: "m1-ultra",
    name: "M1 Ultra",
    vendor: "apple",
    category: "apple-silicon",
    memoryType: "unified",
    memoryGB: 128,
    halfPrecisionTFLOPS: 21.0,
    halfPrecisionFormat: "fp16",
    tf32TFLOPS: null,
    fp32TFLOPS: 21.0,
    fp8TFLOPS: null,
    memoryBandwidthGBps: 800,
    nvlinkBandwidthGBps: null,
    tdpWatts: null,
    gpusPerNode: 1,
    interconnect: "none",
    singleDeviceOnly: true,
    supportsBF16: false,
    supportsTF32: false,
    supportsFP8: false,
  },
  {
    id: "m2-max",
    name: "M2 Max",
    vendor: "apple",
    category: "apple-silicon",
    memoryType: "unified",
    memoryGB: 96,
    halfPrecisionTFLOPS: 13.6,
    halfPrecisionFormat: "fp16",
    tf32TFLOPS: null,
    fp32TFLOPS: 13.6,
    fp8TFLOPS: null,
    memoryBandwidthGBps: 400,
    nvlinkBandwidthGBps: null,
    tdpWatts: null,
    gpusPerNode: 1,
    interconnect: "none",
    singleDeviceOnly: true,
    supportsBF16: false,
    supportsTF32: false,
    supportsFP8: false,
  },
  {
    id: "m2-ultra",
    name: "M2 Ultra",
    vendor: "apple",
    category: "apple-silicon",
    memoryType: "unified",
    memoryGB: 192,
    halfPrecisionTFLOPS: 27.2,
    halfPrecisionFormat: "fp16",
    tf32TFLOPS: null,
    fp32TFLOPS: 27.2,
    fp8TFLOPS: null,
    memoryBandwidthGBps: 800,
    nvlinkBandwidthGBps: null,
    tdpWatts: null,
    gpusPerNode: 1,
    interconnect: "none",
    singleDeviceOnly: true,
    supportsBF16: false,
    supportsTF32: false,
    supportsFP8: false,
  },
  {
    id: "m3-max",
    name: "M3 Max",
    vendor: "apple",
    category: "apple-silicon",
    memoryType: "unified",
    memoryGB: 128,
    halfPrecisionTFLOPS: 14.2,
    halfPrecisionFormat: "fp16",
    tf32TFLOPS: null,
    fp32TFLOPS: 14.2,
    fp8TFLOPS: null,
    memoryBandwidthGBps: 400,
    nvlinkBandwidthGBps: null,
    tdpWatts: null,
    gpusPerNode: 1,
    interconnect: "none",
    singleDeviceOnly: true,
    supportsBF16: false,
    supportsTF32: false,
    supportsFP8: false,
  },
  {
    id: "m3-ultra",
    name: "M3 Ultra",
    vendor: "apple",
    category: "apple-silicon",
    memoryType: "unified",
    memoryGB: 512,
    halfPrecisionTFLOPS: 28.0,
    halfPrecisionFormat: "fp16",
    tf32TFLOPS: null,
    fp32TFLOPS: 28.0,
    fp8TFLOPS: null,
    memoryBandwidthGBps: 819,
    nvlinkBandwidthGBps: null,
    tdpWatts: null,
    gpusPerNode: 1,
    interconnect: "none",
    singleDeviceOnly: true,
    supportsBF16: false,
    supportsTF32: false,
    supportsFP8: false,
  },
  {
    id: "m4-max",
    name: "M4 Max",
    vendor: "apple",
    category: "apple-silicon",
    memoryType: "unified",
    memoryGB: 128,
    halfPrecisionTFLOPS: 16.0,
    halfPrecisionFormat: "fp16",
    tf32TFLOPS: null,
    fp32TFLOPS: 16.0,
    fp8TFLOPS: null,
    memoryBandwidthGBps: 546,
    nvlinkBandwidthGBps: null,
    tdpWatts: null,
    gpusPerNode: 1,
    interconnect: "none",
    singleDeviceOnly: true,
    supportsBF16: false,
    supportsTF32: false,
    supportsFP8: false,
  },
] satisfies GPUSpec[]

const NO_MOE: MoEConfig = {
  enabled: false,
  E: 0,
  topk: 0,
  L_moe: 0,
  E_s: 0,
  loadBalanceFactor: 1.0,
  expertIntermediateSize: null,
  denseIntermediateSize: null,
  activeParameterCount: null,
}

export const MODEL_PRESETS = [
  {
    id: "gpt2-small",
    name: "GPT-2 Small",
    parameterCount: 124e6,
    activeParameterCount: null,
    defaultSequenceLength: 1024,
    architecture: {
      d: 768,
      L: 12,
      a: 12,
      a_kv: 12,
      d_ff: 3072,
      V: 50257,
      ffnType: "standard",
      normType: "layernorm",
      posEmbedding: "learned",
      attentionVariant: "mha",
      tiedEmbeddings: true,
    },
    moe: null,
    notes: "Standard FFN",
  },
  {
    id: "gpt2-medium",
    name: "GPT-2 Medium",
    parameterCount: 350e6,
    activeParameterCount: null,
    defaultSequenceLength: 1024,
    architecture: {
      d: 1024,
      L: 24,
      a: 16,
      a_kv: 16,
      d_ff: 4096,
      V: 50257,
      ffnType: "standard",
      normType: "layernorm",
      posEmbedding: "learned",
      attentionVariant: "mha",
      tiedEmbeddings: true,
    },
    moe: null,
    notes: "Standard FFN",
  },
  {
    id: "gpt2-large",
    name: "GPT-2 Large",
    parameterCount: 774e6,
    activeParameterCount: null,
    defaultSequenceLength: 1024,
    architecture: {
      d: 1280,
      L: 36,
      a: 20,
      a_kv: 20,
      d_ff: 5120,
      V: 50257,
      ffnType: "standard",
      normType: "layernorm",
      posEmbedding: "learned",
      attentionVariant: "mha",
      tiedEmbeddings: true,
    },
    moe: null,
    notes: "Standard FFN",
  },
  {
    id: "gpt2-xl",
    name: "GPT-2 XL",
    parameterCount: 1.56e9,
    activeParameterCount: null,
    defaultSequenceLength: 1024,
    architecture: {
      d: 1600,
      L: 48,
      a: 25,
      a_kv: 25,
      d_ff: 6400,
      V: 50257,
      ffnType: "standard",
      normType: "layernorm",
      posEmbedding: "learned",
      attentionVariant: "mha",
      tiedEmbeddings: true,
    },
    moe: null,
    notes: "Standard FFN",
  },
  {
    id: "llama-7b",
    name: "LLaMA 7B",
    parameterCount: 6.7e9,
    activeParameterCount: null,
    defaultSequenceLength: 2048,
    architecture: {
      d: 4096,
      L: 32,
      a: 32,
      a_kv: 32,
      d_ff: 11008,
      V: 32000,
      ffnType: "swiglu",
      normType: "rmsnorm",
      posEmbedding: "rope",
      attentionVariant: "mha",
      tiedEmbeddings: false,
    },
    moe: null,
    notes: "SwiGLU",
  },
  {
    id: "llama-2-13b",
    name: "LLaMA 2 13B",
    parameterCount: 13e9,
    activeParameterCount: null,
    defaultSequenceLength: 4096,
    architecture: {
      d: 5120,
      L: 40,
      a: 40,
      a_kv: 40,
      d_ff: 13824,
      V: 32000,
      ffnType: "swiglu",
      normType: "rmsnorm",
      posEmbedding: "rope",
      attentionVariant: "mha",
      tiedEmbeddings: false,
    },
    moe: null,
    notes: "SwiGLU",
  },
  {
    id: "llama-2-70b",
    name: "LLaMA 2 70B",
    parameterCount: 70e9,
    activeParameterCount: null,
    defaultSequenceLength: 4096,
    architecture: {
      d: 8192,
      L: 80,
      a: 64,
      a_kv: 8,
      d_ff: 28672,
      V: 32000,
      ffnType: "swiglu",
      normType: "rmsnorm",
      posEmbedding: "rope",
      attentionVariant: "gqa",
      tiedEmbeddings: false,
    },
    moe: null,
    notes: "SwiGLU + GQA",
  },
  {
    id: "mistral-7b",
    name: "Mistral 7B",
    parameterCount: 7.2e9,
    activeParameterCount: null,
    defaultSequenceLength: 8192,
    architecture: {
      d: 4096,
      L: 32,
      a: 32,
      a_kv: 8,
      d_ff: 14336,
      V: 32000,
      ffnType: "swiglu",
      normType: "rmsnorm",
      posEmbedding: "rope",
      attentionVariant: "gqa",
      tiedEmbeddings: false,
    },
    moe: null,
    notes: "SwiGLU + GQA",
  },
  {
    id: "llama-3-8b",
    name: "LLaMA 3 8B",
    parameterCount: 8e9,
    activeParameterCount: null,
    defaultSequenceLength: 8192,
    architecture: {
      d: 4096,
      L: 32,
      a: 32,
      a_kv: 8,
      d_ff: 14336,
      V: 128256,
      ffnType: "swiglu",
      normType: "rmsnorm",
      posEmbedding: "rope",
      attentionVariant: "gqa",
      tiedEmbeddings: false,
    },
    moe: null,
    notes: "SwiGLU + GQA",
  },
  {
    id: "llama-3-70b",
    name: "LLaMA 3 70B",
    parameterCount: 70.6e9,
    activeParameterCount: null,
    defaultSequenceLength: 8192,
    architecture: {
      d: 8192,
      L: 80,
      a: 64,
      a_kv: 8,
      d_ff: 28672,
      V: 128256,
      ffnType: "swiglu",
      normType: "rmsnorm",
      posEmbedding: "rope",
      attentionVariant: "gqa",
      tiedEmbeddings: false,
    },
    moe: null,
    notes: "SwiGLU + GQA",
  },
  {
    id: "llama-3.1-405b",
    name: "LLaMA 3.1 405B",
    parameterCount: 405e9,
    activeParameterCount: null,
    defaultSequenceLength: 131072,
    architecture: {
      d: 16384,
      L: 126,
      a: 128,
      a_kv: 8,
      d_ff: 53248,
      V: 128256,
      ffnType: "swiglu",
      normType: "rmsnorm",
      posEmbedding: "rope",
      attentionVariant: "gqa",
      tiedEmbeddings: false,
    },
    moe: null,
    notes: "SwiGLU + GQA",
  },
  {
    id: "gpt-3-175b",
    name: "GPT-3 175B",
    parameterCount: 175e9,
    activeParameterCount: null,
    defaultSequenceLength: 2048,
    architecture: {
      d: 12288,
      L: 96,
      a: 96,
      a_kv: 96,
      d_ff: 49152,
      V: 50257,
      ffnType: "standard",
      normType: "layernorm",
      posEmbedding: "learned",
      attentionVariant: "mha",
      tiedEmbeddings: false,
    },
    moe: null,
    notes: "Standard FFN",
  },
  {
    id: "qwen-2.5-72b",
    name: "Qwen 2.5 72B",
    parameterCount: 72.7e9,
    activeParameterCount: null,
    defaultSequenceLength: 131072,
    architecture: {
      d: 8192,
      L: 80,
      a: 64,
      a_kv: 8,
      d_ff: 29568,
      V: 152064,
      ffnType: "swiglu",
      normType: "rmsnorm",
      posEmbedding: "rope",
      attentionVariant: "gqa",
      tiedEmbeddings: false,
    },
    moe: null,
    notes: "SwiGLU + GQA",
  },
  {
    id: "deepseek-v3-671b",
    name: "DeepSeek V3 671B",
    parameterCount: 671e9,
    activeParameterCount: 37e9,
    defaultSequenceLength: 131072,
    architecture: {
      d: 7168,
      L: 61,
      a: 128,
      a_kv: null,
      d_ff: null,
      V: 129280,
      ffnType: "moe",
      normType: "rmsnorm",
      posEmbedding: "rope",
      attentionVariant: "mla",
      tiedEmbeddings: false,
    },
    moe: {
      enabled: true,
      E: 256,
      topk: 8,
      L_moe: 58,
      E_s: 1,
      loadBalanceFactor: 1.1,
      expertIntermediateSize: 2048,
      denseIntermediateSize: 18432,
      activeParameterCount: 37e9,
    },
    notes: "MoE (256 experts) + MLA",
  },
] satisfies ModelPreset[]

export const OPTIMIZER_PROFILES = [
  {
    id: "adamw-fp32",
    name: "AdamW fp32",
    description: "Full-fp32 AdamW.",
    fp32Grad: {
      parameterBytes: 4,
      betaGrad: 4,
      masterWeightBytes: 0,
      optimizerStateBytes: 8,
      kOpt: 8,
      phi: 16,
      breakdown: "4 (params) + 4 (grads) + 4 (m) + 4 (v)",
    },
    bf16Grad: {
      parameterBytes: 4,
      betaGrad: 4,
      masterWeightBytes: 0,
      optimizerStateBytes: 8,
      kOpt: 8,
      phi: 16,
      breakdown: "4 (params) + 4 (grads) + 4 (m) + 4 (v)",
    },
    supportsPretraining: true,
    supportsPostTraining: true,
    fixedGradientStorage: true,
  },
  {
    id: "adamw-mixed",
    name: "AdamW mixed",
    description: "Standard mixed-precision AdamW with fp32 master weights.",
    fp32Grad: {
      parameterBytes: 2,
      betaGrad: 4,
      masterWeightBytes: 4,
      optimizerStateBytes: 12,
      kOpt: 12,
      phi: 18,
      breakdown: "2 (params) + 4 (grads) + 4 (master) + 4 (m) + 4 (v)",
    },
    bf16Grad: {
      parameterBytes: 2,
      betaGrad: 2,
      masterWeightBytes: 4,
      optimizerStateBytes: 12,
      kOpt: 12,
      phi: 16,
      breakdown: "2 (params) + 2 (grads) + 4 (master) + 4 (m) + 4 (v)",
    },
    supportsPretraining: true,
    supportsPostTraining: true,
    fixedGradientStorage: false,
  },
  {
    id: "adamw-mixed-bf16-states",
    name: "AdamW mixed (bf16 optimizer states)",
    description: "DeepSeek-style mixed precision with bf16 Adam moments.",
    fp32Grad: {
      parameterBytes: 2,
      betaGrad: 4,
      masterWeightBytes: 4,
      optimizerStateBytes: 8,
      kOpt: 8,
      phi: 14,
      breakdown: "2 (params) + 4 (grads) + 4 (master) + 2 (m) + 2 (v)",
    },
    bf16Grad: {
      parameterBytes: 2,
      betaGrad: 2,
      masterWeightBytes: 4,
      optimizerStateBytes: 8,
      kOpt: 8,
      phi: 12,
      breakdown: "2 (params) + 2 (grads) + 4 (master) + 2 (m) + 2 (v)",
    },
    supportsPretraining: true,
    supportsPostTraining: true,
    fixedGradientStorage: false,
  },
  {
    id: "adamw-mixed-no-master",
    name: "AdamW mixed (no master weights)",
    description: "llm.c-style direct bf16 updates without fp32 master weights.",
    fp32Grad: {
      parameterBytes: 2,
      betaGrad: 4,
      masterWeightBytes: 0,
      optimizerStateBytes: 8,
      kOpt: 8,
      phi: 14,
      breakdown: "2 (params) + 4 (grads) + 4 (m) + 4 (v)",
    },
    bf16Grad: {
      parameterBytes: 2,
      betaGrad: 2,
      masterWeightBytes: 0,
      optimizerStateBytes: 8,
      kOpt: 8,
      phi: 12,
      breakdown: "2 (params) + 2 (grads) + 4 (m) + 4 (v)",
    },
    supportsPretraining: true,
    supportsPostTraining: true,
    fixedGradientStorage: false,
  },
  {
    id: "adamw-fp8",
    name: "AdamW FP8 mixed precision",
    description: "MS-AMP-style fp8 weight and gradient storage.",
    fp32Grad: {
      parameterBytes: 1,
      betaGrad: 1,
      masterWeightBytes: 4,
      optimizerStateBytes: 12,
      kOpt: 12,
      phi: 14,
      breakdown: "1 (params) + 1 (grads) + 4 (master) + 4 (m) + 4 (v)",
    },
    bf16Grad: {
      parameterBytes: 1,
      betaGrad: 1,
      masterWeightBytes: 4,
      optimizerStateBytes: 12,
      kOpt: 12,
      phi: 14,
      breakdown: "1 (params) + 1 (grads) + 4 (master) + 4 (m) + 4 (v)",
    },
    supportsPretraining: true,
    supportsPostTraining: true,
    fixedGradientStorage: true,
  },
  {
    id: "adamw-8bit",
    name: "AdamW + 8-bit states",
    description: "bitsandbytes 8-bit AdamW states.",
    fp32Grad: {
      parameterBytes: 2,
      betaGrad: 4,
      masterWeightBytes: 4,
      optimizerStateBytes: 6,
      kOpt: 6,
      phi: 12,
      breakdown: "2 (params) + 4 (grads) + 4 (master) + 1 (m) + 1 (v)",
    },
    bf16Grad: {
      parameterBytes: 2,
      betaGrad: 2,
      masterWeightBytes: 4,
      optimizerStateBytes: 6,
      kOpt: 6,
      phi: 10,
      breakdown: "2 (params) + 2 (grads) + 4 (master) + 1 (m) + 1 (v)",
    },
    supportsPretraining: true,
    supportsPostTraining: true,
    fixedGradientStorage: false,
  },
  {
    id: "adam-mini",
    name: "Adam-mini",
    description: "Block-diagonal optimizer-state approximation.",
    fp32Grad: {
      parameterBytes: 2,
      betaGrad: 4,
      masterWeightBytes: 4,
      optimizerStateBytes: 6,
      kOpt: 6,
      phi: 12,
      breakdown: "2 (params) + 4 (grads) + 4 (master) + ~2 (optimizer state)",
    },
    bf16Grad: {
      parameterBytes: 2,
      betaGrad: 2,
      masterWeightBytes: 4,
      optimizerStateBytes: 6,
      kOpt: 6,
      phi: 10,
      breakdown: "2 (params) + 2 (grads) + 4 (master) + ~2 (optimizer state)",
    },
    supportsPretraining: true,
    supportsPostTraining: true,
    fixedGradientStorage: false,
  },
  {
    id: "sgd-momentum",
    name: "SGD + momentum",
    description: "Mixed-precision SGD with momentum.",
    fp32Grad: {
      parameterBytes: 2,
      betaGrad: 4,
      masterWeightBytes: 4,
      optimizerStateBytes: 8,
      kOpt: 8,
      phi: 14,
      breakdown: "2 (params) + 4 (grads) + 4 (master) + 4 (momentum)",
    },
    bf16Grad: {
      parameterBytes: 2,
      betaGrad: 2,
      masterWeightBytes: 4,
      optimizerStateBytes: 8,
      kOpt: 8,
      phi: 12,
      breakdown: "2 (params) + 2 (grads) + 4 (master) + 4 (momentum)",
    },
    supportsPretraining: true,
    supportsPostTraining: true,
    fixedGradientStorage: false,
  },
  {
    id: "sgd-no-momentum",
    name: "SGD (no momentum)",
    description: "Mixed-precision SGD without momentum.",
    fp32Grad: {
      parameterBytes: 2,
      betaGrad: 4,
      masterWeightBytes: 4,
      optimizerStateBytes: 4,
      kOpt: 4,
      phi: 10,
      breakdown: "2 (params) + 4 (grads) + 4 (master)",
    },
    bf16Grad: {
      parameterBytes: 2,
      betaGrad: 2,
      masterWeightBytes: 4,
      optimizerStateBytes: 4,
      kOpt: 4,
      phi: 8,
      breakdown: "2 (params) + 2 (grads) + 4 (master)",
    },
    supportsPretraining: true,
    supportsPostTraining: true,
    fixedGradientStorage: false,
  },
  {
    id: "adafactor",
    name: "Adafactor",
    description: "Factored second-moment optimizer states.",
    fp32Grad: {
      parameterBytes: 2,
      betaGrad: 4,
      masterWeightBytes: 4,
      optimizerStateBytes: 8,
      kOpt: 8,
      phi: 14,
      breakdown: "2 (params) + 4 (grads) + 4 (master) + 4 (factored state)",
    },
    bf16Grad: {
      parameterBytes: 2,
      betaGrad: 2,
      masterWeightBytes: 4,
      optimizerStateBytes: 8,
      kOpt: 8,
      phi: 12,
      breakdown: "2 (params) + 2 (grads) + 4 (master) + 4 (factored state)",
    },
    supportsPretraining: true,
    supportsPostTraining: true,
    fixedGradientStorage: false,
  },
  {
    id: "lion",
    name: "Lion",
    description: "Momentum-only optimizer states.",
    fp32Grad: {
      parameterBytes: 2,
      betaGrad: 4,
      masterWeightBytes: 4,
      optimizerStateBytes: 8,
      kOpt: 8,
      phi: 14,
      breakdown: "2 (params) + 4 (grads) + 4 (master) + 4 (momentum)",
    },
    bf16Grad: {
      parameterBytes: 2,
      betaGrad: 2,
      masterWeightBytes: 4,
      optimizerStateBytes: 8,
      kOpt: 8,
      phi: 12,
      breakdown: "2 (params) + 2 (grads) + 4 (master) + 4 (momentum)",
    },
    supportsPretraining: true,
    supportsPostTraining: true,
    fixedGradientStorage: false,
  },
  {
    id: "lamb",
    name: "LAMB",
    description: "AdamW-like state footprint for large-batch training.",
    fp32Grad: {
      parameterBytes: 2,
      betaGrad: 4,
      masterWeightBytes: 4,
      optimizerStateBytes: 12,
      kOpt: 12,
      phi: 18,
      breakdown: "2 (params) + 4 (grads) + 4 (master) + 4 (m) + 4 (v)",
    },
    bf16Grad: {
      parameterBytes: 2,
      betaGrad: 2,
      masterWeightBytes: 4,
      optimizerStateBytes: 12,
      kOpt: 12,
      phi: 16,
      breakdown: "2 (params) + 2 (grads) + 4 (master) + 4 (m) + 4 (v)",
    },
    supportsPretraining: true,
    supportsPostTraining: true,
    fixedGradientStorage: false,
  },
  {
    id: "mezo",
    name: "MeZO",
    description: "Zeroth-order fine-tuning without gradients or optimizer states.",
    fp32Grad: {
      parameterBytes: 2,
      betaGrad: 0,
      masterWeightBytes: 0,
      optimizerStateBytes: 0,
      kOpt: 0,
      phi: 2,
      breakdown: "2 (params only)",
    },
    bf16Grad: {
      parameterBytes: 2,
      betaGrad: 0,
      masterWeightBytes: 0,
      optimizerStateBytes: 0,
      kOpt: 0,
      phi: 2,
      breakdown: "2 (params only)",
    },
    supportsPretraining: false,
    supportsPostTraining: true,
    fixedGradientStorage: true,
  },
] satisfies OptimizerProfile[]

export const QUICK_MODE_LOOKUP = [
  {
    id: "lt-500m",
    minParams: 0,
    maxParams: 500e6,
    heads: 12,
    layers: 12,
    family: "dense-gpt-style",
  },
  {
    id: "500m-2b",
    minParams: 500e6,
    maxParams: 2e9,
    heads: 16,
    layers: 24,
    family: "dense-gpt-style",
  },
  {
    id: "2b-5b",
    minParams: 2e9,
    maxParams: 5e9,
    heads: 32,
    layers: 24,
    family: "modern-open-weights",
  },
  {
    id: "5b-10b",
    minParams: 5e9,
    maxParams: 10e9,
    heads: 32,
    layers: 32,
    family: "modern-open-weights",
  },
  {
    id: "10b-24b",
    minParams: 10e9,
    maxParams: 24e9,
    heads: 40,
    layers: 40,
    family: "modern-open-weights",
  },
  {
    id: "24b-55b",
    minParams: 24e9,
    maxParams: 55e9,
    heads: 64,
    layers: 48,
    family: "modern-open-weights",
  },
  {
    id: "gte-55b",
    minParams: 55e9,
    maxParams: Number.POSITIVE_INFINITY,
    heads: 64,
    layers: 80,
    family: "modern-open-weights",
  },
] satisfies QuickModeLookup[]

export const CHINCHILLA_COEFFICIENTS = [
  {
    id: "chinchilla-corrected",
    label: "Chinchilla (corrected Epoch AI, ~20x)",
    alpha: 0.3478,
    beta: 0.3658,
    A: 482.01,
    B: 2085.43,
    E: 1.8172,
    autoSelectMinDNRatio: 0,
    autoSelectMaxDNRatio: 30,
    autoSelectable: true,
  },
  {
    id: "overtraining-100x",
    label: "D/N <= 100",
    alpha: 0.08,
    beta: 0.13,
    A: 7.199,
    B: 25.97,
    E: 0.17,
    autoSelectMinDNRatio: 30,
    autoSelectMaxDNRatio: 100,
    autoSelectable: true,
  },
  {
    id: "overtraining-250x",
    label: "D/N <= 250",
    alpha: 0.13,
    beta: 0.16,
    A: 14.23,
    B: 39.54,
    E: 0.98,
    autoSelectMinDNRatio: 100,
    autoSelectMaxDNRatio: 250,
    autoSelectable: true,
  },
  {
    id: "overtraining-500x",
    label: "D/N <= 500",
    alpha: 0.13,
    beta: 0.16,
    A: 17.07,
    B: 35.8,
    E: 0.95,
    autoSelectMinDNRatio: 250,
    autoSelectMaxDNRatio: 500,
    autoSelectable: true,
  },
  {
    id: "all-data",
    label: "All Data (up to 10,000x)",
    alpha: 0.18,
    beta: 0.24,
    A: 33.66,
    B: 138.9,
    E: 1.45,
    autoSelectMinDNRatio: 500,
    autoSelectMaxDNRatio: null,
    autoSelectable: true,
  },
  {
    id: "chinchilla-original",
    label: "Chinchilla (original published, ~20x)",
    alpha: 0.34,
    beta: 0.28,
    A: 406.4,
    B: 410.7,
    E: 1.69,
    autoSelectMinDNRatio: null,
    autoSelectMaxDNRatio: null,
    autoSelectable: false,
  },
] satisfies ChinchillaCoefficients[]

export const MFU_DEFAULTS = [
  {
    id: "small-model",
    label: "Small model (<1B), 1-8 GPUs",
    minParams: 0,
    maxParams: 1e9,
    minGPUs: 1,
    maxGPUs: 8,
    mfuLow: 0.25,
    mfuHigh: 0.35,
    defaultMFU: 0.35,
    advisoryOnly: false,
  },
  {
    id: "medium-model",
    label: "Medium model (1B-10B), 8-64 GPUs",
    minParams: 1e9,
    maxParams: 10e9,
    minGPUs: 8,
    maxGPUs: 64,
    mfuLow: 0.35,
    mfuHigh: 0.45,
    defaultMFU: 0.45,
    advisoryOnly: false,
  },
  {
    id: "large-model",
    label: "Large model (10B-100B), 64-512 GPUs",
    minParams: 10e9,
    maxParams: 100e9,
    minGPUs: 64,
    maxGPUs: 512,
    mfuLow: 0.4,
    mfuHigh: 0.5,
    defaultMFU: 0.5,
    advisoryOnly: false,
  },
  {
    id: "very-large-model",
    label: "Very large (100B+), 512+ GPUs",
    minParams: 100e9,
    maxParams: null,
    minGPUs: 512,
    maxGPUs: null,
    mfuLow: 0.35,
    mfuHigh: 0.45,
    defaultMFU: 0.43,
    advisoryOnly: false,
  },
  {
    id: "state-of-the-art",
    label: "State-of-the-art (PaLM-scale)",
    minParams: null,
    maxParams: null,
    minGPUs: null,
    maxGPUs: null,
    mfuLow: 0.45,
    mfuHigh: 0.55,
    defaultMFU: 0.5,
    advisoryOnly: true,
  },
] satisfies MFUDefault[]

export const CLOUD_PRICING_PRESETS = [
  {
    id: "v100-32gb",
    gpuId: "v100-32gb",
    label: "V100 32GB",
    priceLow: 1.5,
    priceHigh: 2.5,
    priceDefault: 2.0,
  },
  {
    id: "a100-80gb",
    gpuId: "a100-80gb",
    label: "A100 80GB",
    priceLow: 2.5,
    priceHigh: 4.0,
    priceDefault: 3.25,
  },
  {
    id: "h100-sxm",
    gpuId: "h100-sxm",
    label: "H100 SXM",
    priceLow: 3.0,
    priceHigh: 5.0,
    priceDefault: 4.0,
  },
  {
    id: "h200-sxm",
    gpuId: "h200-sxm",
    label: "H200 SXM",
    priceLow: 4.0,
    priceHigh: 6.0,
    priceDefault: 5.0,
  },
  {
    id: "b200",
    gpuId: "b200-hgx",
    label: "B200",
    priceLow: 5.0,
    priceHigh: 8.0,
    priceDefault: 6.5,
  },
] satisfies CloudPricingPreset[]

export const CLOUD_INSTANCES = [
  // On-demand instance-hour list prices in representative US regions.
  // GCP: Iowa (us-central1); Azure: East US Linux; Lambda: public 1x price.
  {
    id: "aws-p4d-24xlarge",
    provider: "AWS",
    instanceType: "p4d.24xlarge",
    gpuId: "a100-40gb",
    gpuCount: 8,
    vramPerGPU: 40,
    pricePerHour: 21.957642,
  },
  {
    id: "aws-g5-xlarge",
    provider: "AWS",
    instanceType: "g5.xlarge",
    gpuId: "a10g",
    gpuCount: 1,
    vramPerGPU: 24,
    pricePerHour: 1.006,
  },
  {
    id: "gcp-a2-highgpu-1g",
    provider: "GCP",
    instanceType: "a2-highgpu-1g",
    gpuId: "a100-40gb",
    gpuCount: 1,
    vramPerGPU: 40,
    pricePerHour: 3.673385,
  },
  {
    id: "gcp-g2-standard-4",
    provider: "GCP",
    instanceType: "g2-standard-4",
    gpuId: "l4",
    gpuCount: 1,
    vramPerGPU: 24,
    pricePerHour: 0.706832276,
  },
  {
    id: "azure-standard-nc8as-t4-v3",
    provider: "Azure",
    instanceType: "Standard_NC8as_T4_v3",
    gpuId: "t4",
    gpuCount: 1,
    vramPerGPU: 16,
    pricePerHour: 0.752,
  },
  {
    id: "lambda-gpu-1x-a100-sxm4",
    provider: "Lambda",
    instanceType: "gpu_1x_a100_sxm4",
    gpuId: "a100-40gb",
    gpuCount: 1,
    vramPerGPU: 40,
    pricePerHour: 1.99,
  },
] satisfies CloudInstance[]

export const DEFAULT_LORA_TARGET_MODULES = [
  "q_proj",
  "k_proj",
  "v_proj",
  "o_proj",
  "gate_proj",
  "up_proj",
  "down_proj",
] satisfies LoRATargetModule[]

const DEFAULT_GPU = GPU_SPECS.find((gpu) => gpu.id === "h100-sxm") as GPUSpec
const DEFAULT_MODEL_PRESET = MODEL_PRESETS.find(
  (preset) => preset.id === "llama-3-8b"
) as ModelPreset

const DEFAULT_ARCHITECTURE: ModelArchitecture = {
  ...DEFAULT_MODEL_PRESET.architecture,
}

const DEFAULT_MOE_CONFIG: MoEConfig = {
  ...NO_MOE,
}

const DEFAULT_QUICK_MODE: QuickModeConfig = {
  totalParameters: DEFAULT_MODEL_PRESET.parameterCount,
  family: "modern-open-weights",
  inferredHeads: 32,
  inferredLayers: 32,
  hiddenSizeRoundingMultiple: 128,
}

const DEFAULT_PARALLELISM: ParallelismConfig = {
  N_tp: 1,
  N_pp: 1,
  N_dp: 8,
  N_cp: 1,
  N_ep: 1,
  zeroStage: 1,
  fsdpStrategy: null,
  framework: "deepspeed",
  sequenceParallelism: "auto",
  VP: 1,
}

const DEFAULT_ZERO_COMMUNICATION: ZeROCommunicationConfig = {
  mode: "hf-auto",
  overlapComm: false,
  allgatherBucketSizeElements: 4096 * 4096,
  reduceBucketSizeElements: 4096 * 4096,
  prefetchBucketSizeElements: Math.floor(0.9 * 4096 * 4096),
}

export const INTER_NODE_BANDWIDTH_PRESETS = [
  { id: "hdr-200", label: "HDR 200 Gb/s", bandwidthGBps: 25 },
  { id: "ndr-400", label: "NDR 400 Gb/s", bandwidthGBps: 50 },
] as const

export const DEFAULT_FP8_CONFIG: FP8Config = {
  kernelSpeedupFactor: 1.3,
  storageMode: "transformer-engine",
}

export const DEFAULT_TRAINING_CONFIG: TrainingConfig = {
  model: {
    inputMode: "preset",
    presetId: DEFAULT_MODEL_PRESET.id,
    quickMode: DEFAULT_QUICK_MODE,
    architecture: DEFAULT_ARCHITECTURE,
    moe: DEFAULT_MOE_CONFIG,
  },
  totalTokens: 1e12,
  uniqueTokens: 1e12,
  precision: "bf16",
  optimizer: "adamw-mixed",
  gradientPrecision: "fp32",
  microBatchSize: 4,
  sequenceLength: DEFAULT_MODEL_PRESET.defaultSequenceLength,
  gradientAccumulationSteps: 8,
  activationCheckpointing: "selective",
  partialCheckpointDepth: null,
  flashAttention: true,
  hardware: {
    inputMode: "preset",
    gpuId: DEFAULT_GPU.id,
    gpu: DEFAULT_GPU,
    numGPUs: 8,
    targetTrainingDays: null,
  },
  mfuOverride: null,
  parallelismMode: "auto",
  parallelism: DEFAULT_PARALLELISM,
  pricing: {
    costPerGPUHour: 4.0,
    checkpointRetentionCount: 5,
    storagePricePerGBMonth: 0.023,
    datasetStorageGB: 0,
    cloudPricingPresetId: "h100-sxm",
    cloudInstanceId: null,
  },
  ampAutocast: false,
  cpuOffload: "none",
  zeroCommunication: DEFAULT_ZERO_COMMUNICATION,
  interNodeBandwidth: {
    mode: "ndr-400",
    customGBps: 50,
  },
  torchCompile: false,
  chunkedCrossEntropy: false,
  fp8: DEFAULT_FP8_CONFIG,
  failureModel: {
    failureRatePerInstancePerDay: 0.01,
    recoveryTimeHours: 1,
    checkpointFrequencyPerDay: 24,
  },
}

export const DEFAULT_POST_TRAINING_CONFIG: PostTrainingConfig = {
  baseModel: {
    inputMode: "preset",
    presetId: DEFAULT_MODEL_PRESET.id,
    parameterCount: DEFAULT_MODEL_PRESET.parameterCount,
    architecture: DEFAULT_ARCHITECTURE,
    moe: DEFAULT_MOE_CONFIG,
  },
  method: "sft",
  approach: "lora",
  lora: {
    rank: 16,
    alpha: 32,
    targetModules: [...DEFAULT_LORA_TARGET_MODULES],
    quantizationBits: null,
  },
  trainableParameterPercentage: null,
  ppo: {
    criticModelParameterCount: DEFAULT_MODEL_PRESET.parameterCount,
    rewardModelParameterCount: DEFAULT_MODEL_PRESET.parameterCount,
    updateEpochs: 4,
  },
  grpo: {
    groupSize: 8,
  },
  datasetSizeExamples: 50000,
  epochs: 3,
  sequenceLength: 4096,
  batchSize: 8,
  hardware: {
    inputMode: "preset",
    gpuId: DEFAULT_GPU.id,
    gpu: DEFAULT_GPU,
    numGPUs: 1,
  },
  precision: "bf16",
  optimizer: "adamw-mixed",
  gradientPrecision: "fp32",
  chunkedCrossEntropy: false,
  fp8: DEFAULT_FP8_CONFIG,
  costPerGPUHour: 4.0,
  kvCachePrecision: "bf16",
}
