import type {
  GPUSpec,
  ModelPreset,
  OptimizerProfile,
  QuickModeLookup,
  ChinchillaCoefficients,
  MFUDefault,
  CloudPricingPreset,
  CloudInstance,
  TrainingConfig,
  MoEConfig,
  ParallelismConfig,
  ModelArchitecture,
} from "./types"

// ─── GPU Specifications (Section 7) ─────────���────────────────────────────────

export const GPU_SPECS: GPUSpec[] = [
  // NVIDIA Datacenter
  {
    name: "V100 32GB",
    vendor: "nvidia",
    category: "datacenter",
    vram: 32,
    tflops_bf16: 125,
    tflops_tf32: null,
    tflops_fp8: null,
    memBandwidth: 900,
    nvlinkBandwidth: 300,
    tdp: 300,
    gpusPerNode: 8,
    interconnect: "nvlink",
  },
  {
    name: "A100 PCIe 80GB",
    vendor: "nvidia",
    category: "datacenter",
    vram: 80,
    tflops_bf16: 312,
    tflops_tf32: 156,
    tflops_fp8: null,
    memBandwidth: 2039,
    nvlinkBandwidth: null,
    tdp: 300,
    gpusPerNode: 8,
    interconnect: "pcie",
  },
  {
    name: "A100 40GB",
    vendor: "nvidia",
    category: "datacenter",
    vram: 40,
    tflops_bf16: 312,
    tflops_tf32: 156,
    tflops_fp8: null,
    memBandwidth: 1555,
    nvlinkBandwidth: 600,
    tdp: 400,
    gpusPerNode: 8,
    interconnect: "nvlink",
  },
  {
    name: "A100 80GB",
    vendor: "nvidia",
    category: "datacenter",
    vram: 80,
    tflops_bf16: 312,
    tflops_tf32: 156,
    tflops_fp8: null,
    memBandwidth: 2039,
    nvlinkBandwidth: 600,
    tdp: 400,
    gpusPerNode: 8,
    interconnect: "nvlink",
  },
  {
    name: "H100 PCIe 80GB",
    vendor: "nvidia",
    category: "datacenter",
    vram: 80,
    tflops_bf16: 989,
    tflops_tf32: 378,
    tflops_fp8: 1979,
    memBandwidth: 2039,
    nvlinkBandwidth: null,
    tdp: 350,
    gpusPerNode: 8,
    interconnect: "pcie",
  },
  {
    name: "H100 SXM",
    vendor: "nvidia",
    category: "datacenter",
    vram: 80,
    tflops_bf16: 989,
    tflops_tf32: 495,
    tflops_fp8: 1979,
    memBandwidth: 3350,
    nvlinkBandwidth: 900,
    tdp: 700,
    gpusPerNode: 8,
    interconnect: "nvlink",
  },
  {
    name: "H100 NVL",
    vendor: "nvidia",
    category: "datacenter",
    vram: 94,
    tflops_bf16: 989,
    tflops_tf32: 495,
    tflops_fp8: 1979,
    memBandwidth: 3350,
    nvlinkBandwidth: 900,
    tdp: 800,
    gpusPerNode: 8,
    interconnect: "nvlink",
  },
  {
    name: "H200 SXM",
    vendor: "nvidia",
    category: "datacenter",
    vram: 141,
    tflops_bf16: 989,
    tflops_tf32: 495,
    tflops_fp8: 1979,
    memBandwidth: 4800,
    nvlinkBandwidth: 900,
    tdp: 700,
    gpusPerNode: 8,
    interconnect: "nvlink",
  },
  {
    name: "B200 (HGX)",
    vendor: "nvidia",
    category: "datacenter",
    vram: 180,
    tflops_bf16: 2250,
    tflops_tf32: 1125,
    tflops_fp8: 4500,
    memBandwidth: 7700,
    nvlinkBandwidth: 1800,
    tdp: 1000,
    gpusPerNode: 8,
    interconnect: "nvlink",
  },
  {
    name: "B200 (NVL72)",
    vendor: "nvidia",
    category: "datacenter",
    vram: 186,
    tflops_bf16: 2500,
    tflops_tf32: 1250,
    tflops_fp8: 5000,
    memBandwidth: 8000,
    nvlinkBandwidth: 1800,
    tdp: 1200,
    gpusPerNode: 8,
    interconnect: "nvlink",
  },
  {
    name: "T4",
    vendor: "nvidia",
    category: "datacenter",
    vram: 16,
    tflops_bf16: 65,
    tflops_tf32: null,
    tflops_fp8: null,
    memBandwidth: 320,
    nvlinkBandwidth: null,
    tdp: 70,
    gpusPerNode: 1,
    interconnect: "pcie",
  },
  {
    name: "A10G",
    vendor: "nvidia",
    category: "datacenter",
    vram: 24,
    tflops_bf16: 70,
    tflops_tf32: 35,
    tflops_fp8: null,
    memBandwidth: 600,
    nvlinkBandwidth: null,
    tdp: 300,
    gpusPerNode: 1,
    interconnect: "pcie",
  },
  {
    name: "L4",
    vendor: "nvidia",
    category: "datacenter",
    vram: 24,
    tflops_bf16: 121,
    tflops_tf32: 60,
    tflops_fp8: 242,
    memBandwidth: 300,
    nvlinkBandwidth: null,
    tdp: 72,
    gpusPerNode: 1,
    interconnect: "pcie",
  },
  {
    name: "L40S",
    vendor: "nvidia",
    category: "datacenter",
    vram: 48,
    tflops_bf16: 362,
    tflops_tf32: 183,
    tflops_fp8: null,
    memBandwidth: 864,
    nvlinkBandwidth: null,
    tdp: 350,
    gpusPerNode: 1,
    interconnect: "pcie",
  },

  // NVIDIA Consumer
  {
    name: "RTX 4090",
    vendor: "nvidia",
    category: "consumer",
    vram: 24,
    tflops_bf16: 165,
    tflops_tf32: 83,
    tflops_fp8: null,
    memBandwidth: 1008,
    nvlinkBandwidth: null,
    tdp: 450,
    gpusPerNode: 1,
    interconnect: "pcie",
  },
  {
    name: "RTX 4080",
    vendor: "nvidia",
    category: "consumer",
    vram: 16,
    tflops_bf16: 97,
    tflops_tf32: 49,
    tflops_fp8: null,
    memBandwidth: 717,
    nvlinkBandwidth: null,
    tdp: 320,
    gpusPerNode: 1,
    interconnect: "pcie",
  },
  {
    name: "RTX 3090",
    vendor: "nvidia",
    category: "consumer",
    vram: 24,
    tflops_bf16: 71,
    tflops_tf32: 36,
    tflops_fp8: null,
    memBandwidth: 936,
    nvlinkBandwidth: null,
    tdp: 350,
    gpusPerNode: 1,
    interconnect: "pcie",
  },
  {
    name: "RTX 3060 12GB",
    vendor: "nvidia",
    category: "consumer",
    vram: 12,
    tflops_bf16: 25,
    tflops_tf32: 13,
    tflops_fp8: null,
    memBandwidth: 360,
    nvlinkBandwidth: null,
    tdp: 170,
    gpusPerNode: 1,
    interconnect: "pcie",
  },

  // AMD
  {
    name: "MI250X",
    vendor: "amd",
    category: "amd",
    vram: 128,
    tflops_bf16: 383,
    tflops_tf32: null,
    tflops_fp8: null,
    memBandwidth: 3276,
    nvlinkBandwidth: null,
    tdp: 560,
    gpusPerNode: 8,
    interconnect: "pcie",
  },
  {
    name: "MI300X",
    vendor: "amd",
    category: "amd",
    vram: 192,
    tflops_bf16: 1307,
    tflops_tf32: null,
    tflops_fp8: 2614,
    memBandwidth: 5300,
    nvlinkBandwidth: null,
    tdp: 750,
    gpusPerNode: 8,
    interconnect: "pcie",
  },

  // Apple Silicon (Section 7 — unified memory)
  {
    name: "M1 Max",
    vendor: "apple",
    category: "apple",
    vram: 64,
    tflops_bf16: 10.4,
    tflops_tf32: null,
    tflops_fp8: null,
    memBandwidth: 400,
    nvlinkBandwidth: null,
    tdp: 60,
    gpusPerNode: 1,
    interconnect: "none",
  },
  {
    name: "M1 Ultra",
    vendor: "apple",
    category: "apple",
    vram: 128,
    tflops_bf16: 21.0,
    tflops_tf32: null,
    tflops_fp8: null,
    memBandwidth: 800,
    nvlinkBandwidth: null,
    tdp: 120,
    gpusPerNode: 1,
    interconnect: "none",
  },
  {
    name: "M2 Max",
    vendor: "apple",
    category: "apple",
    vram: 96,
    tflops_bf16: 13.6,
    tflops_tf32: null,
    tflops_fp8: null,
    memBandwidth: 400,
    nvlinkBandwidth: null,
    tdp: 75,
    gpusPerNode: 1,
    interconnect: "none",
  },
  {
    name: "M2 Ultra",
    vendor: "apple",
    category: "apple",
    vram: 192,
    tflops_bf16: 27.2,
    tflops_tf32: null,
    tflops_fp8: null,
    memBandwidth: 800,
    nvlinkBandwidth: null,
    tdp: 150,
    gpusPerNode: 1,
    interconnect: "none",
  },
  {
    name: "M3 Max",
    vendor: "apple",
    category: "apple",
    vram: 128,
    tflops_bf16: 14.2,
    tflops_tf32: null,
    tflops_fp8: null,
    memBandwidth: 400,
    nvlinkBandwidth: null,
    tdp: 80,
    gpusPerNode: 1,
    interconnect: "none",
  },
  {
    name: "M3 Ultra",
    vendor: "apple",
    category: "apple",
    vram: 512,
    tflops_bf16: 28.0,
    tflops_tf32: null,
    tflops_fp8: null,
    memBandwidth: 800,
    nvlinkBandwidth: null,
    tdp: 160,
    gpusPerNode: 1,
    interconnect: "none",
  },
  {
    name: "M4 Max",
    vendor: "apple",
    category: "apple",
    vram: 128,
    tflops_bf16: 16.0,
    tflops_tf32: null,
    tflops_fp8: null,
    memBandwidth: 546,
    nvlinkBandwidth: null,
    tdp: 85,
    gpusPerNode: 1,
    interconnect: "none",
  },
]

// ─── Model Architecture Presets (Section 3.3) ────────��───────────────────────

/** Default MoE config (disabled) */
const NO_MOE: MoEConfig = {
  enabled: false,
  E: 0,
  topk: 0,
  L_moe: 0,
  E_s: 0,
  loadBalanceFactor: 1.0,
}

export const MODEL_PRESETS: ModelPreset[] = [
  {
    name: "GPT-2 Small (124M)",
    approxParams: 124e6,
    architecture: {
      d: 768,
      L: 12,
      a: 12,
      a_kv: 12,
      d_ff: 3072,
      V: 50257,
      s: 1024,
      ffnType: "standard",
      normType: "layernorm",
      posEmbedding: "learned",
      tiedEmbeddings: true,
    },
    moe: null,
  },
  {
    name: "GPT-2 Medium (350M)",
    approxParams: 350e6,
    architecture: {
      d: 1024,
      L: 24,
      a: 16,
      a_kv: 16,
      d_ff: 4096,
      V: 50257,
      s: 1024,
      ffnType: "standard",
      normType: "layernorm",
      posEmbedding: "learned",
      tiedEmbeddings: true,
    },
    moe: null,
  },
  {
    name: "GPT-2 Large (774M)",
    approxParams: 774e6,
    architecture: {
      d: 1280,
      L: 36,
      a: 20,
      a_kv: 20,
      d_ff: 5120,
      V: 50257,
      s: 1024,
      ffnType: "standard",
      normType: "layernorm",
      posEmbedding: "learned",
      tiedEmbeddings: true,
    },
    moe: null,
  },
  {
    name: "GPT-2 XL (1.56B)",
    approxParams: 1.56e9,
    architecture: {
      d: 1600,
      L: 48,
      a: 25,
      a_kv: 25,
      d_ff: 6400,
      V: 50257,
      s: 1024,
      ffnType: "standard",
      normType: "layernorm",
      posEmbedding: "learned",
      tiedEmbeddings: true,
    },
    moe: null,
  },
  {
    name: "LLaMA 7B",
    approxParams: 6.7e9,
    architecture: {
      d: 4096,
      L: 32,
      a: 32,
      a_kv: 32,
      d_ff: 11008,
      V: 32000,
      s: 2048,
      ffnType: "swiglu",
      normType: "rmsnorm",
      posEmbedding: "rope",
      tiedEmbeddings: false,
    },
    moe: null,
  },
  {
    name: "LLaMA 2 13B",
    approxParams: 13e9,
    architecture: {
      d: 5120,
      L: 40,
      a: 40,
      a_kv: 40,
      d_ff: 13824,
      V: 32000,
      s: 4096,
      ffnType: "swiglu",
      normType: "rmsnorm",
      posEmbedding: "rope",
      tiedEmbeddings: false,
    },
    moe: null,
  },
  {
    name: "LLaMA 2 70B",
    approxParams: 70e9,
    architecture: {
      d: 8192,
      L: 80,
      a: 64,
      a_kv: 8,
      d_ff: 28672,
      V: 32000,
      s: 4096,
      ffnType: "swiglu",
      normType: "rmsnorm",
      posEmbedding: "rope",
      tiedEmbeddings: false,
    },
    moe: null,
  },
  {
    name: "Mistral 7B",
    approxParams: 7.2e9,
    architecture: {
      d: 4096,
      L: 32,
      a: 32,
      a_kv: 8,
      d_ff: 14336,
      V: 32000,
      s: 8192,
      ffnType: "swiglu",
      normType: "rmsnorm",
      posEmbedding: "rope",
      tiedEmbeddings: false,
    },
    moe: null,
  },
  {
    name: "LLaMA 3 8B",
    approxParams: 8e9,
    architecture: {
      d: 4096,
      L: 32,
      a: 32,
      a_kv: 8,
      d_ff: 14336,
      V: 128256,
      s: 8192,
      ffnType: "swiglu",
      normType: "rmsnorm",
      posEmbedding: "rope",
      tiedEmbeddings: false,
    },
    moe: null,
  },
  {
    name: "LLaMA 3 70B",
    approxParams: 70.6e9,
    architecture: {
      d: 8192,
      L: 80,
      a: 64,
      a_kv: 8,
      d_ff: 28672,
      V: 128256,
      s: 8192,
      ffnType: "swiglu",
      normType: "rmsnorm",
      posEmbedding: "rope",
      tiedEmbeddings: false,
    },
    moe: null,
  },
  {
    name: "LLaMA 3.1 405B",
    approxParams: 405e9,
    architecture: {
      d: 16384,
      L: 126,
      a: 128,
      a_kv: 8,
      d_ff: 53248,
      V: 128256,
      s: 8192,
      ffnType: "swiglu",
      normType: "rmsnorm",
      posEmbedding: "rope",
      tiedEmbeddings: false,
    },
    moe: null,
  },
  {
    name: "GPT-3 175B",
    approxParams: 175e9,
    architecture: {
      d: 12288,
      L: 96,
      a: 96,
      a_kv: 96,
      d_ff: 49152,
      V: 50257,
      s: 2048,
      ffnType: "standard",
      normType: "layernorm",
      posEmbedding: "learned",
      tiedEmbeddings: false,
    },
    moe: null,
  },
  {
    name: "Qwen 2.5 72B",
    approxParams: 72.7e9,
    architecture: {
      d: 8192,
      L: 80,
      a: 64,
      a_kv: 8,
      d_ff: 29568,
      V: 152064,
      s: 32768,
      ffnType: "swiglu",
      normType: "rmsnorm",
      posEmbedding: "rope",
      tiedEmbeddings: false,
    },
    moe: null,
  },
  {
    name: "DeepSeek V3 671B (MoE)",
    approxParams: 671e9,
    architecture: {
      d: 7168,
      L: 61,
      a: 128,
      a_kv: 128,
      d_ff: 18432,
      V: 129280,
      s: 4096,
      ffnType: "swiglu",
      normType: "rmsnorm",
      posEmbedding: "rope",
      tiedEmbeddings: false,
    },
    moe: {
      enabled: true,
      E: 256,
      topk: 8,
      L_moe: 58,
      E_s: 1,
      loadBalanceFactor: 1.1,
    },
  },
]

// ─── Optimizer Memory Profiles (Section 5.1) ─────────────────────────────────
// Φ = total bytes/param = param_bytes + β_grad + optimizer_state_bytes
// K_opt = optimizer state bytes/param (sharded in ZeRO-1)
// β_grad: 4 for fp32 gradients, 2 for bf16 gradients

export const OPTIMIZER_PROFILES: OptimizerProfile[] = [
  {
    name: "AdamW (Full FP32)",
    type: "adamw_fp32",
    // 4 (param) + 4 (grad) + 4 (master=param) + 4 (m) + 4 (v) = 16 (no separate master)
    phi_fp32grad: 16,
    phi_bf16grad: 16,
    K_opt: 8, // m + v
    beta_grad_fp32: 4,
    beta_grad_bf16: 4, // full fp32 always uses fp32 grads
    breakdown: "4 (param fp32) + 4 (grad fp32) + 4 (m) + 4 (v)",
    supportsPretraining: true,
  },
  {
    name: "AdamW (Mixed Precision)",
    type: "adamw_mixed",
    // fp32 grads: 2 (param bf16) + 4 (grad fp32) + 4 (master fp32) + 4 (m) + 4 (v) = 18
    phi_fp32grad: 18,
    // bf16 grads: 2 (param bf16) + 2 (grad bf16) + 4 (master fp32) + 4 (m) + 4 (v) = 16
    phi_bf16grad: 16,
    K_opt: 12, // master weights + m + v
    beta_grad_fp32: 4,
    beta_grad_bf16: 2,
    breakdown: "2 (bf16) + β_grad + 4 (master) + 4 (m) + 4 (v)",
    supportsPretraining: true,
  },
  {
    name: "AdamW 8-bit (bitsandbytes)",
    type: "adamw_8bit",
    // 2 (param bf16) + 2 (grad bf16) + 4 (master fp32) + 1 (m int8) + 1 (v int8) = 10
    phi_fp32grad: 12, // 2 + 4 + 4 + 1 + 1
    phi_bf16grad: 10, // 2 + 2 + 4 + 1 + 1
    K_opt: 6, // master + int8 m + int8 v
    beta_grad_fp32: 4,
    beta_grad_bf16: 2,
    breakdown: "2 (bf16) + ��_grad + 4 (master) + 1 (m int8) + 1 (v int8)",
    supportsPretraining: true,
  },
  {
    name: "AdamW FP8 (MS-AMP)",
    type: "adamw_fp8",
    // 1 (fp8 param) + 1 (fp8 grad) + 4 (master) + 4 (m) + 4 (v) = 14
    phi_fp32grad: 14,
    phi_bf16grad: 14,
    K_opt: 12, // master + m + v
    beta_grad_fp32: 1,
    beta_grad_bf16: 1,
    breakdown: "1 (fp8) + 1 (fp8 grad) + 4 (master) + 4 (m) + 4 (v)",
    supportsPretraining: true,
  },
  {
    name: "Adam-mini",
    type: "adam_mini",
    // 2 (param bf16) + 2 (grad bf16) + 4 (master) + ~2 (block-diagonal momentum)
    phi_fp32grad: 12, // 2 + 4 + 4 + 2
    phi_bf16grad: 10, // 2 + 2 + 4 + 2
    K_opt: 6, // master + reduced momentum
    beta_grad_fp32: 4,
    beta_grad_bf16: 2,
    breakdown: "2 (bf16) + β_grad + 4 (master) + ~2 (block-diag)",
    supportsPretraining: true,
  },
  {
    name: "SGD + Momentum (Mixed)",
    type: "sgd_momentum",
    // 2 (param bf16) + β_grad + 4 (master fp32) + 4 (momentum fp32) = 12 or 14
    phi_fp32grad: 14,
    phi_bf16grad: 12,
    K_opt: 8, // master + momentum
    beta_grad_fp32: 4,
    beta_grad_bf16: 2,
    breakdown: "2 (bf16) + β_grad + 4 (master) + 4 (momentum)",
    supportsPretraining: true,
  },
  {
    name: "SGD (No Momentum, Mixed)",
    type: "sgd_no_momentum",
    // 2 (param bf16) + β_grad + 4 (master fp32)
    phi_fp32grad: 10,
    phi_bf16grad: 8,
    K_opt: 4, // master weights only
    beta_grad_fp32: 4,
    beta_grad_bf16: 2,
    breakdown: "2 (bf16) + β_grad + 4 (master)",
    supportsPretraining: true,
  },
  {
    name: "Adafactor",
    type: "adafactor",
    // 2 (param bf16) + β_grad + 4 (master) + 4 (row+col factors)
    phi_fp32grad: 14,
    phi_bf16grad: 12,
    K_opt: 8, // master + factors
    beta_grad_fp32: 4,
    beta_grad_bf16: 2,
    breakdown: "2 (bf16) + ��_grad + 4 (master) + 4 (row+col factors)",
    supportsPretraining: true,
  },
  {
    name: "Lion (Mixed)",
    type: "lion",
    // 2 (param bf16) + β_grad + 4 (master) + 4 (momentum only)
    phi_fp32grad: 14,
    phi_bf16grad: 12,
    K_opt: 8, // master + momentum
    beta_grad_fp32: 4,
    beta_grad_bf16: 2,
    breakdown: "2 (bf16) + β_grad + 4 (master) + 4 (momentum)",
    supportsPretraining: true,
  },
  {
    name: "LAMB (Mixed)",
    type: "lamb",
    // Same as AdamW mixed: 2 + β_grad + 4 + 4 + 4
    phi_fp32grad: 18,
    phi_bf16grad: 16,
    K_opt: 12,
    beta_grad_fp32: 4,
    beta_grad_bf16: 2,
    breakdown: "2 (bf16) + β_grad + 4 (master) + 4 (m) + 4 (v)",
    supportsPretraining: true,
  },
  {
    name: "MeZO (Zeroth-Order)",
    type: "mezo",
    // 2 (param bf16) + 0 (no grads) + 0 (no optimizer states)
    phi_fp32grad: 2,
    phi_bf16grad: 2,
    K_opt: 0,
    beta_grad_fp32: 0,
    beta_grad_bf16: 0,
    breakdown: "2 (bf16 params only, no gradients or optimizer states)",
    supportsPretraining: false, // fine-tuning only
  },
]

// ─── Quick Mode Lookup (Section 11.1) ────────────────────────────────────────

export const QUICK_MODE_LOOKUP: QuickModeLookup[] = [
  { minParams: 0, maxParams: 500e6, heads: 12, layers: 12 },
  { minParams: 500e6, maxParams: 2e9, heads: 16, layers: 24 },
  { minParams: 2e9, maxParams: 5e9, heads: 32, layers: 24 },
  { minParams: 5e9, maxParams: 10e9, heads: 32, layers: 32 },
  { minParams: 10e9, maxParams: 24e9, heads: 40, layers: 40 },
  { minParams: 24e9, maxParams: 55e9, heads: 64, layers: 48 },
  { minParams: 55e9, maxParams: Infinity, heads: 64, layers: 80 },
]

// ─── Chinchilla Coefficients (Section 4.3 sensitivity table) ─────────────────

export const CHINCHILLA_COEFFICIENTS: ChinchillaCoefficients[] = [
  {
    label: "Overtraining ≤100x",
    maxDNRatio: 100,
    alpha: 0.08,
    beta: 0.13,
    A: 7.199,
    B: 25.97,
    E: 0.17,
  },
  {
    label: "Overtraining ≤250x",
    maxDNRatio: 250,
    alpha: 0.13,
    beta: 0.16,
    A: 14.23,
    B: 39.54,
    E: 0.98,
  },
  {
    label: "Overtraining ≤500x",
    maxDNRatio: 500,
    alpha: 0.13,
    beta: 0.16,
    A: 17.07,
    B: 35.80,
    E: 0.95,
  },
  {
    label: "All Data (up to 10,000x)",
    maxDNRatio: 10000,
    alpha: 0.18,
    beta: 0.24,
    A: 33.66,
    B: 138.9,
    E: 1.45,
  },
  {
    label: "Chinchilla (corrected, Epoch AI)",
    maxDNRatio: 30,
    alpha: 0.3478,
    beta: 0.3658,
    A: 482.01,
    B: 2085.43,
    E: 1.8172,
  },
  {
    label: "Chinchilla (original published)",
    maxDNRatio: 30,
    alpha: 0.34,
    beta: 0.28,
    A: 406.4,
    B: 410.7,
    E: 1.69,
  },
]

// ─── MFU Defaults (Section 6.3) ───────────���─────────────────────────────────

export const MFU_DEFAULTS: MFUDefault[] = [
  {
    label: "Small model (<1B), 1-8 GPUs",
    minParams: 0,
    maxParams: 1e9,
    minGPUs: 1,
    maxGPUs: 8,
    mfu: 0.30,
  },
  {
    label: "Medium model (1B-10B), 8-64 GPUs",
    minParams: 1e9,
    maxParams: 10e9,
    minGPUs: 8,
    maxGPUs: 64,
    mfu: 0.40,
  },
  {
    label: "Large model (10B-100B), 64-512 GPUs",
    minParams: 10e9,
    maxParams: 100e9,
    minGPUs: 64,
    maxGPUs: 512,
    mfu: 0.45,
  },
  {
    label: "Very large (100B+), 512+ GPUs",
    minParams: 100e9,
    maxParams: Infinity,
    minGPUs: 512,
    maxGPUs: Infinity,
    mfu: 0.40,
  },
]

// ─── Cloud Pricing Presets (Section 8.1) ───────────────���─────────────────────

export const CLOUD_PRICING_PRESETS: CloudPricingPreset[] = [
  { gpu: "V100 32GB", priceLow: 1.50, priceHigh: 2.50, priceDefault: 2.00 },
  { gpu: "A100 80GB", priceLow: 2.50, priceHigh: 4.00, priceDefault: 3.25 },
  { gpu: "H100 SXM", priceLow: 3.00, priceHigh: 5.00, priceDefault: 4.00 },
  { gpu: "H200 SXM", priceLow: 4.00, priceHigh: 6.00, priceDefault: 5.00 },
  { gpu: "B200", priceLow: 5.00, priceHigh: 8.00, priceDefault: 6.50 },
]

export const CLOUD_INSTANCES: CloudInstance[] = [
  {
    provider: "AWS",
    instanceType: "p4d.24xlarge",
    gpu: "A100",
    gpuCount: 8,
    vramPerGPU: 40,
    pricePerHour: 24.15,
  },
  {
    provider: "AWS",
    instanceType: "g5.xlarge",
    gpu: "A10G",
    gpuCount: 1,
    vramPerGPU: 24,
    pricePerHour: 1.01,
  },
  {
    provider: "GCP",
    instanceType: "a2-highgpu-1g",
    gpu: "A100",
    gpuCount: 1,
    vramPerGPU: 40,
    pricePerHour: 2.95,
  },
  {
    provider: "GCP",
    instanceType: "g2-standard-4",
    gpu: "L4",
    gpuCount: 1,
    vramPerGPU: 24,
    pricePerHour: 0.99,
  },
  {
    provider: "Azure",
    instanceType: "Standard_NC8as_T4_v3",
    gpu: "T4",
    gpuCount: 1,
    vramPerGPU: 16,
    pricePerHour: 0.90,
  },
  {
    provider: "Lambda",
    instanceType: "gpu_1x_a100_sxm5",
    gpu: "A100",
    gpuCount: 1,
    vramPerGPU: 80,
    pricePerHour: 1.99,
  },
]

// ─── Default Configuration ───────────────��───────────────────────────────────

const DEFAULT_GPU = GPU_SPECS.find((g) => g.name === "H100 SXM")!

const DEFAULT_ARCHITECTURE: ModelArchitecture = {
  d: 4096,
  L: 32,
  a: 32,
  a_kv: 8,
  d_ff: 14336,
  V: 128256,
  s: 8192,
  ffnType: "swiglu",
  normType: "rmsnorm",
  posEmbedding: "rope",
  tiedEmbeddings: false,
}

const DEFAULT_MOE: MoEConfig = {
  enabled: false,
  E: 0,
  topk: 0,
  L_moe: 0,
  E_s: 0,
  loadBalanceFactor: 1.1,
}

const DEFAULT_PARALLELISM: ParallelismConfig = {
  N_tp: 1,
  N_pp: 1,
  N_dp: 1,
  N_cp: 1,
  N_ep: 1,
  zeroStage: 1,
  framework: "deepspeed",
  sequenceParallelism: false,
  VP: 1,
}

export const DEFAULT_TRAINING_CONFIG: TrainingConfig = {
  // Model
  modelInputMode: "preset",
  architecture: DEFAULT_ARCHITECTURE,
  moe: DEFAULT_MOE,

  // Dataset
  totalTokens: 2e12, // 2T tokens
  uniqueTokens: 2e12,

  // Precision & Optimizer
  precision: "bf16",
  optimizer: "adamw_mixed",
  gradientPrecision: "fp32",

  // Batch & Sequence
  microBatchSize: 4,
  sequenceLength: 8192,
  gradAccumSteps: 8,

  // Memory optimizations
  checkpointing: "selective",
  flashAttention: true,

  // Hardware
  gpu: DEFAULT_GPU,
  numGPUs: 8,
  targetTrainingDays: null,

  // Efficiency
  mfuOverride: null,

  // Parallelism
  parallelismMode: "auto",
  parallelism: DEFAULT_PARALLELISM,

  // Cost
  costPerGPUHour: 4.0,

  // Advanced inputs
  partialCheckpointDepth: null,
  ampAutocast: false,
  cpuOffload: "none",
  overlapComm: true,
  interNodeBandwidth: 200, // HDR default
  torchCompile: false,
  chunkedCrossEntropy: false,
  fp8SpeedupFactor: 1.3,
  fp8Mode: "transformer_engine",
  kvCachePrecision: "bf16",
  checkpointRetention: 5,
  failureRate: 0.01,
  recoveryTimeHours: 1.0,
  checkpointFrequency: 24,
  storagePricePerGBMonth: 0.023,
}
